; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Feb 25 2020 00:47:55 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAWFXFS0KJ6B:
	dc.w DATAWFXFS0KJ6B_0-DATAWFXFS0KJ6B, DATAWFXFS0KJ6B_1-DATAWFXFS0KJ6B
	dc.w DATAWFXFS0KJ6B_2-DATAWFXFS0KJ6B, DATAWFXFS0KJ6B_3-DATAWFXFS0KJ6B
DATAWFXFS0KJ6B_0: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAWFXFS0KJ6B_1: dc.b $2
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
DATAWFXFS0KJ6B_2: dc.b $8
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
DATAWFXFS0KJ6B_3: dc.b $2
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
	even