; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Feb 22 2020 08:09:15 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA3SSO83C8UPK:
	dc.w DATA3SSO83C8UPK_0-DATA3SSO83C8UPK, DATA3SSO83C8UPK_1-DATA3SSO83C8UPK
	dc.w DATA3SSO83C8UPK_2-DATA3SSO83C8UPK, DATA3SSO83C8UPK_3-DATA3SSO83C8UPK
	dc.w DATA3SSO83C8UPK_4-DATA3SSO83C8UPK, DATA3SSO83C8UPK_5-DATA3SSO83C8UPK
DATA3SSO83C8UPK_0: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $C, $0, $10, $F0
DATA3SSO83C8UPK_1: dc.b $2
	dc.b $F4, $F, $0, $14, $F0
	dc.b $EC, $C, $0, $24, $F0
DATA3SSO83C8UPK_2: dc.b $2
	dc.b $F8, $F, $0, $28, $F0
	dc.b $F0, $C, $0, $38, $F0
DATA3SSO83C8UPK_3: dc.b $1
	dc.b $EC, $F, $0, $3C, $F0
DATA3SSO83C8UPK_4: dc.b $3
	dc.b $F4, $E, $88, $4C, $F8
	dc.b $C, $C, $88, $58, $F8
	dc.b $F4, $3, $88, $5C, $F0
DATA3SSO83C8UPK_5: dc.b $3
	dc.b $F4, $E, $80, $4C, $EE
	dc.b $C, $C, $80, $58, $EE
	dc.b $F4, $3, $80, $5C, $E
	even