; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jan 20 2020 09:46:11 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAOB6ZKAE3A4J:
	dc.w DATAOB6ZKAE3A4J_0-DATAOB6ZKAE3A4J, DATAOB6ZKAE3A4J_1-DATAOB6ZKAE3A4J
	dc.w DATAOB6ZKAE3A4J_2-DATAOB6ZKAE3A4J, DATAOB6ZKAE3A4J_3-DATAOB6ZKAE3A4J
DATAOB6ZKAE3A4J_0: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $C, $0, $10, $F0
DATAOB6ZKAE3A4J_1: dc.b $2
	dc.b $F4, $F, $0, $14, $F0
	dc.b $EC, $C, $0, $24, $F0
DATAOB6ZKAE3A4J_2: dc.b $3
	dc.b $F4, $F, $0, $28, $F0
	dc.b $EC, $C, $0, $38, $F0
	dc.b $FC, $2, $0, $4C, $10
DATAOB6ZKAE3A4J_3: dc.b $1
	dc.b $EC, $F, $0, $3C, $F0
	even