; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Apr 10 2020 15:15:51 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA136ZGBYR9LV:
	dc.w DATA136ZGBYR9LV_0-DATA136ZGBYR9LV, DATA136ZGBYR9LV_1-DATA136ZGBYR9LV
	dc.w DATA136ZGBYR9LV_2-DATA136ZGBYR9LV, DATA136ZGBYR9LV_3-DATA136ZGBYR9LV
	dc.w DATA136ZGBYR9LV_4-DATA136ZGBYR9LV, DATA136ZGBYR9LV_5-DATA136ZGBYR9LV
	dc.w DATA136ZGBYR9LV_6-DATA136ZGBYR9LV, DATA136ZGBYR9LV_7-DATA136ZGBYR9LV
DATA136ZGBYR9LV_0: dc.b $5
	dc.b $F8, $D, $0, $25, $BC
	dc.b $F8, $D, $0, $2D, $DC
	dc.b $F8, $D, $0, $35, $FC
	dc.b $F8, $D, $0, $3D, $1C
	dc.b $F8, $1, $0, $45, $3C
DATA136ZGBYR9LV_1: dc.b $3
	dc.b $4, $5, $0, $15, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATA136ZGBYR9LV_2: dc.b $3
	dc.b $4, $5, $0, $19, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATA136ZGBYR9LV_3: dc.b $3
	dc.b $4, $5, $0, $1D, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATA136ZGBYR9LV_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATA136ZGBYR9LV_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA136ZGBYR9LV_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATA136ZGBYR9LV_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even