; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 12 2020 10:18:33 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAY9DC2STVLKR:
	dc.w DATAY9DC2STVLKR_0-DATAY9DC2STVLKR
DATAY9DC2STVLKR_0: dc.b $5
	dc.b $4, $D, $0, $0, $E0
	dc.b $EC, $E, $0, $8, $E8
	dc.b $4, $D, $0, $14, $0
	dc.b $EC, $2, $0, $1C, $8
	dc.b $F4, $1, $0, $1F, $10
	even