; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Feb 09 2020 04:57:18 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATADIVVU6X9CUI:
	dc.w DATADIVVU6X9CUI_0-DATADIVVU6X9CUI, DATADIVVU6X9CUI_1-DATADIVVU6X9CUI
	dc.w DATADIVVU6X9CUI_2-DATADIVVU6X9CUI, DATADIVVU6X9CUI_3-DATADIVVU6X9CUI
DATADIVVU6X9CUI_0: dc.b $1
	dc.b $80, $9, $80, $30, $0
DATADIVVU6X9CUI_1: dc.b $2
	dc.b $80, $9, $80, $30, $0
	dc.b $88, $D, $81, $E, $0
DATADIVVU6X9CUI_2: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A0, $1, $80, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
DATADIVVU6X9CUI_3: dc.b $A
	dc.b $80, $D, $80, $0, $0
	dc.b $80, $D, $80, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A0, $1, $A0, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $81, $E, $10
	even