; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Feb 16 2020 06:43:32 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATALS172BVSBTR:
	dc.w DATALS172BVSBTR_0-DATALS172BVSBTR, DATALS172BVSBTR_1-DATALS172BVSBTR
	dc.w DATALS172BVSBTR_2-DATALS172BVSBTR, DATALS172BVSBTR_3-DATALS172BVSBTR
	dc.w DATALS172BVSBTR_4-DATALS172BVSBTR, DATALS172BVSBTR_5-DATALS172BVSBTR
	dc.w DATALS172BVSBTR_6-DATALS172BVSBTR, DATALS172BVSBTR_7-DATALS172BVSBTR
	dc.w DATALS172BVSBTR_8-DATALS172BVSBTR, DATALS172BVSBTR_9-DATALS172BVSBTR
	dc.w DATALS172BVSBTR_A-DATALS172BVSBTR
DATALS172BVSBTR_0: dc.b $3
	dc.b $EC, $D, $0, $0, $EC
	dc.b $F4, $0, $0, $8, $C
	dc.b $FC, $E, $0, $9, $F4
DATALS172BVSBTR_1: dc.b $3
	dc.b $EC, $6, $0, $15, $EC
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $A, $0, $21, $FC
DATALS172BVSBTR_2: dc.b $3
	dc.b $EC, $6, $0, $2A, $EC
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $A, $0, $21, $FC
DATALS172BVSBTR_3: dc.b $4
	dc.b $EC, $6, $0, $30, $EC
	dc.b $EC, $9, $0, $1B, $FC
	dc.b $FC, $9, $0, $36, $FC
	dc.b $C, $0, $0, $3C, $C
DATALS172BVSBTR_4: dc.b $3
	dc.b $F4, $D, $0, $3D, $EC
	dc.b $FC, $0, $0, $20, $C
	dc.b $4, $8, $0, $45, $FC
DATALS172BVSBTR_5: dc.b $2
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
DATALS172BVSBTR_6: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $FE, $0, $0, $52, $14
DATALS172BVSBTR_7: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $FE, $4, $0, $53, $14
DATALS172BVSBTR_8: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $FE, $0, $E0, $52, $14
DATALS172BVSBTR_9: dc.b $3
	dc.b $F8, $D, $0, $48, $EC
	dc.b $F8, $1, $0, $50, $C
	dc.b $FE, $4, $E0, $53, $14
DATALS172BVSBTR_A: dc.b $0
	even