; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Dec 25 2020 12:49:32 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAO3VRYAGUSQA:
	dc.w DATAO3VRYAGUSQA_0-DATAO3VRYAGUSQA, DATAO3VRYAGUSQA_1-DATAO3VRYAGUSQA
	dc.w DATAO3VRYAGUSQA_2-DATAO3VRYAGUSQA, DATAO3VRYAGUSQA_3-DATAO3VRYAGUSQA
DATAO3VRYAGUSQA_0: dc.b $7
	dc.b $E1, $0, $0, $F6, $30
	dc.b $E1, $0, $0, $F2, $38
	dc.b $E1, $0, $0, $F7, $40
	dc.b $E1, $0, $0, $F5, $48
	dc.b $E1, $0, $0, $FA, $50
	dc.b $E1, $0, $0, $F2, $58
	dc.b $E1, $0, $0, $FB, $60
DATAO3VRYAGUSQA_1: dc.b $E
	dc.b $0, $C, $0, $F0, $4
	dc.b $0, $0, $0, $F3, $24
	dc.b $0, $0, $0, $F3, $34
	dc.b $E1, $0, $0, $F1, $30
	dc.b $E1, $0, $0, $F2, $38
	dc.b $E1, $0, $0, $F7, $40
	dc.b $0, $8, $0, $F4, $3C
	dc.b $0, $0, $0, $F4, $54
	dc.b $E1, $0, $0, $FA, $50
	dc.b $E1, $0, $0, $F5, $48
	dc.b $E1, $0, $0, $F2, $58
	dc.b $E1, $0, $0, $FB, $60
	dc.b $0, $4, $0, $F8, $64
	dc.b $0, $C, $0, $FC, $74
DATAO3VRYAGUSQA_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
DATAO3VRYAGUSQA_3: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
	even