; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Feb 18 2020 18:23:56 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAED8VBV3V7QU:
	dc.w $0, DATAED8VBV3V7QU_1-DATAED8VBV3V7QU
	dc.w DATAED8VBV3V7QU_2-DATAED8VBV3V7QU, DATAED8VBV3V7QU_3-DATAED8VBV3V7QU
DATAED8VBV3V7QU_1: dc.b $6
	dc.b $0, $C, $0, $F0, $0
	dc.b $0, $0, $0, $F3, $20
	dc.b $0, $0, $0, $F3, $30
	dc.b $0, $C, $0, $F4, $38
	dc.b $0, $8, $0, $F8, $60
	dc.b $0, $8, $0, $FB, $78
DATAED8VBV3V7QU_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
DATAED8VBV3V7QU_3: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
	even