; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Jan 20 2020 13:18:04 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA05YGYIPN6T5M:
	dc.w DATA05YGYIPN6T5M_0-DATA05YGYIPN6T5M
DATA05YGYIPN6T5M_0: dc.b $2D
	dc.b $DC, $D, $0, $0, $7C
	dc.b $F4, $D, $0, $8, $7C
	dc.b $24, $9, $0, $10, $7C
	dc.b $4, $7, $0, $16, $84
	dc.b $CC, $9, $0, $1E, $94
	dc.b $DC, $E, $0, $24, $A4
	dc.b $F4, $7, $0, $30, $A4
	dc.b $14, $7, $0, $38, $A4
	dc.b $F4, $1, $0, $40, $B4
	dc.b $24, $D, $0, $42, $B4
	dc.b $D4, $4, $0, $4A, $BC
	dc.b $DC, $0, $0, $4C, $C4
	dc.b $FC, $D, $0, $4D, $C4
	dc.b $C, $6, $0, $55, $CC
	dc.b $24, $1, $0, $5B, $D4
	dc.b $C, $C, $0, $5D, $DC
	dc.b $F4, $A, $0, $61, $E4
	dc.b $EC, $C, $0, $6A, $EC
	dc.b $1C, $5, $0, $6E, $F4
	dc.b $E4, $C, $0, $72, $FC
	dc.b $FC, $3, $0, $76, $FC
	dc.b $4, $C, $0, $7A, $4
	dc.b $D4, $5, $0, $7E, $C
	dc.b $EC, $E, $0, $82, $C
	dc.b $C, $F, $0, $8E, $C
	dc.b $2C, $C, $0, $9E, $C
	dc.b $DC, $D, $0, $A2, $1C
	dc.b $D4, $4, $0, $AA, $24
	dc.b $4, $C, $0, $AC, $24
	dc.b $EC, $A, $0, $B0, $2C
	dc.b $C, $7, $0, $B9, $2C
	dc.b $2C, $8, $0, $C1, $34
	dc.b $DC, $D, $0, $C4, $3C
	dc.b $C, $0, $0, $CC, $3C
	dc.b $1C, $D, $0, $CD, $3C
	dc.b $F4, $E, $0, $D5, $44
	dc.b $EC, $8, $0, $E1, $4C
	dc.b $C, $D, $0, $E4, $4C
	dc.b $DC, $D, $0, $EC, $5C
	dc.b $1C, $D, $0, $F4, $5C
	dc.b $F4, $9, $0, $FC, $64
	dc.b $4, $4, $1, $2, $64
	dc.b $D4, $0, $1, $4, $6C
	dc.b $C, $1, $1, $5, $6C
	dc.b $1C, $0, $1, $7, $7C
	even