; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Feb 14 2020 17:47:16 GMT-0600 (Central Standard Time)
; ================================================================================

DATAYLJY3NIDEO:
	dc.w DATAYLJY3NIDEO_0-DATAYLJY3NIDEO
DATAYLJY3NIDEO_0: dc.b $2A
	dc.b $DD, $F, $20, $0, $86
	dc.b $FD, $D, $20, $10, $86
	dc.b $2D, $8, $20, $18, $86
	dc.b $D, $7, $20, $1B, $8E
	dc.b $35, $0, $20, $23, $8D
	dc.b $D5, $8, $20, $24, $9E
	dc.b $DD, $C, $20, $27, $A6
	dc.b $E5, $B, $20, $2B, $AE
	dc.b $5, $7, $20, $37, $AE
	dc.b $25, $D, $20, $3F, $AE
	dc.b $5, $0, $20, $47, $BE
	dc.b $D5, $3, $20, $48, $C6
	dc.b $DD, $0, $20, $4C, $CE
	dc.b $FD, $A, $20, $4D, $CC
	dc.b $25, $9, $20, $56, $CC
	dc.b $15, $5, $20, $5C, $D4
	dc.b $5, $D, $20, $60, $E1
	dc.b $E, $C, $20, $68, $FC
	dc.b $DE, $7, $20, $6C, $C
	dc.b $FE, $D, $20, $74, $C
	dc.b $16, $F, $20, $7C, $C
	dc.b $E6, $E, $20, $8C, $1C
	dc.b $E, $C, $20, $98, $1C
	dc.b $DE, $4, $20, $9C, $24
	dc.b $FE, $D, $20, $9E, $2C
	dc.b $16, $7, $20, $A6, $2C
	dc.b $E6, $C, $20, $AE, $3C
	dc.b $EE, $1, $20, $B2, $3B
	dc.b $E, $1, $20, $B4, $3B
	dc.b $26, $D, $20, $B6, $3C
	dc.b $1E, $C, $20, $BE, $44
	dc.b $DE, $C, $20, $C2, $4C
	dc.b $EE, $C, $20, $C6, $4C
	dc.b $FE, $F, $20, $CA, $4C
	dc.b $F6, $C, $20, $DA, $54
	dc.b $E6, $C, $20, $DE, $5C
	dc.b $26, $D, $20, $E2, $5C
	dc.b $1E, $C, $20, $EA, $64
	dc.b $DE, $4, $20, $EE, $6C
	dc.b $FE, $3, $20, $F0, $6C
	dc.b $F6, $1, $20, $F4, $74
	dc.b $26, $0, $20, $F6, $7C
	even