; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Feb 23 2020 08:46:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA0CWNL9WK61OM:
	dc.w DATA0CWNL9WK61OM_0-DATA0CWNL9WK61OM, DATA0CWNL9WK61OM_1-DATA0CWNL9WK61OM
	dc.w DATA0CWNL9WK61OM_2-DATA0CWNL9WK61OM, DATA0CWNL9WK61OM_3-DATA0CWNL9WK61OM
	dc.w DATA0CWNL9WK61OM_4-DATA0CWNL9WK61OM, DATA0CWNL9WK61OM_5-DATA0CWNL9WK61OM
	dc.w DATA0CWNL9WK61OM_6-DATA0CWNL9WK61OM, DATA0CWNL9WK61OM_7-DATA0CWNL9WK61OM
DATA0CWNL9WK61OM_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATA0CWNL9WK61OM_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATA0CWNL9WK61OM_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATA0CWNL9WK61OM_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATA0CWNL9WK61OM_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATA0CWNL9WK61OM_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATA0CWNL9WK61OM_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F8
DATA0CWNL9WK61OM_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F8
	even