; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Apr 28 2020 10:00:41 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAB2CGIM1MIS:
	dc.w $0, DATAB2CGIM1MIS_1-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_2-DATAB2CGIM1MIS, DATAB2CGIM1MIS_3-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_4-DATAB2CGIM1MIS, DATAB2CGIM1MIS_5-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_6-DATAB2CGIM1MIS, DATAB2CGIM1MIS_7-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_8-DATAB2CGIM1MIS, DATAB2CGIM1MIS_9-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_A-DATAB2CGIM1MIS, DATAB2CGIM1MIS_B-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_C-DATAB2CGIM1MIS, DATAB2CGIM1MIS_D-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_E-DATAB2CGIM1MIS, DATAB2CGIM1MIS_F-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_10-DATAB2CGIM1MIS, DATAB2CGIM1MIS_11-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_12-DATAB2CGIM1MIS, DATAB2CGIM1MIS_13-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_14-DATAB2CGIM1MIS, DATAB2CGIM1MIS_15-DATAB2CGIM1MIS
	dc.w DATAB2CGIM1MIS_16-DATAB2CGIM1MIS
DATAB2CGIM1MIS_1: dc.b $6
	dc.b $ED, $8, $0, $0, $F0
	dc.b $F5, $D, $0, $3, $F0
	dc.b $5, $8, $0, $B, $F0
	dc.b $D, $8, $0, $E, $F8
	dc.b $D, $0, $0, $11, $F0
	dc.b $5, $0, $0, $12, $8
DATAB2CGIM1MIS_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAB2CGIM1MIS_3: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATAB2CGIM1MIS_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $ED, $9, $0, $9, $F3
	dc.b $F7, $0, $0, $F, $B
DATAB2CGIM1MIS_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATAB2CGIM1MIS_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EB
	dc.b $EC, $9, $0, $C, $F3
	dc.b $F6, $0, $0, $12, $B
DATAB2CGIM1MIS_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAB2CGIM1MIS_8: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAB2CGIM1MIS_9: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAB2CGIM1MIS_A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAB2CGIM1MIS_B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATAB2CGIM1MIS_C: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATAB2CGIM1MIS_D: dc.b $1
	dc.b $F2, $F, $0, $0, $F1
DATAB2CGIM1MIS_E: dc.b $1
	dc.b $EE, $F, $0, $0, $F0
DATAB2CGIM1MIS_F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAB2CGIM1MIS_10: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATAB2CGIM1MIS_11: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAB2CGIM1MIS_12: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATAB2CGIM1MIS_13: dc.b $4
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
	dc.b $F0, $0, $0, $12, $C
DATAB2CGIM1MIS_14: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATAB2CGIM1MIS_15: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATAB2CGIM1MIS_16: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
	even