; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Aug 24 2020 22:01:26 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATATO9WBSMIMW:
	dc.w $0, DATATO9WBSMIMW_1-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_2-DATATO9WBSMIMW, DATATO9WBSMIMW_3-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_4-DATATO9WBSMIMW, DATATO9WBSMIMW_5-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_6-DATATO9WBSMIMW, DATATO9WBSMIMW_7-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_8-DATATO9WBSMIMW, DATATO9WBSMIMW_9-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_A-DATATO9WBSMIMW, DATATO9WBSMIMW_B-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_C-DATATO9WBSMIMW, DATATO9WBSMIMW_D-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_E-DATATO9WBSMIMW, DATATO9WBSMIMW_F-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_10-DATATO9WBSMIMW, DATATO9WBSMIMW_11-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_12-DATATO9WBSMIMW, DATATO9WBSMIMW_13-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_14-DATATO9WBSMIMW, DATATO9WBSMIMW_15-DATATO9WBSMIMW
	dc.w DATATO9WBSMIMW_16-DATATO9WBSMIMW
DATATO9WBSMIMW_1: dc.b $6
	dc.b $ED, $8, $0, $0, $F0
	dc.b $F5, $D, $0, $3, $F0
	dc.b $5, $8, $0, $B, $F0
	dc.b $D, $8, $0, $E, $F8
	dc.b $D, $0, $0, $11, $F0
	dc.b $5, $0, $0, $12, $8
DATATO9WBSMIMW_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATATO9WBSMIMW_3: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATATO9WBSMIMW_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $F7, $0, $0, $9, $B
	dc.b $ED, $9, $0, $A, $F3
DATATO9WBSMIMW_5: dc.b $6
	dc.b $B, $4, $0, $0, $EC
	dc.b $FB, $9, $0, $2, $EC
	dc.b $FB, $0, $0, $8, $4
	dc.b $3, $1, $0, $9, $4
	dc.b $FB, $2, $0, $B, $C
	dc.b $EB, $9, $0, $E, $F4
DATATO9WBSMIMW_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EB
	dc.b $F6, $0, $0, $C, $B
	dc.b $EC, $9, $0, $D, $F3
DATATO9WBSMIMW_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATATO9WBSMIMW_8: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATATO9WBSMIMW_9: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATATO9WBSMIMW_A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATATO9WBSMIMW_B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATATO9WBSMIMW_C: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATATO9WBSMIMW_D: dc.b $1
	dc.b $F2, $F, $0, $0, $F1
DATATO9WBSMIMW_E: dc.b $1
	dc.b $EE, $F, $0, $0, $F0
DATATO9WBSMIMW_F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATATO9WBSMIMW_10: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATATO9WBSMIMW_11: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATATO9WBSMIMW_12: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATATO9WBSMIMW_13: dc.b $4
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
	dc.b $F0, $0, $0, $12, $C
DATATO9WBSMIMW_14: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATATO9WBSMIMW_15: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATATO9WBSMIMW_16: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
	even