; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jan 07 2020 00:52:16 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA652SPLWCU7D:
	dc.w $0, DATA652SPLWCU7D_1-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_2-DATA652SPLWCU7D, DATA652SPLWCU7D_3-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_4-DATA652SPLWCU7D, DATA652SPLWCU7D_5-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_6-DATA652SPLWCU7D, DATA652SPLWCU7D_7-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_8-DATA652SPLWCU7D, DATA652SPLWCU7D_9-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_A-DATA652SPLWCU7D, DATA652SPLWCU7D_B-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_C-DATA652SPLWCU7D, DATA652SPLWCU7D_D-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_E-DATA652SPLWCU7D, DATA652SPLWCU7D_F-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_10-DATA652SPLWCU7D, DATA652SPLWCU7D_11-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_12-DATA652SPLWCU7D, DATA652SPLWCU7D_13-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_14-DATA652SPLWCU7D, DATA652SPLWCU7D_15-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_16-DATA652SPLWCU7D, DATA652SPLWCU7D_17-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_18-DATA652SPLWCU7D, DATA652SPLWCU7D_19-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_1A-DATA652SPLWCU7D, DATA652SPLWCU7D_1B-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_1C-DATA652SPLWCU7D, DATA652SPLWCU7D_1D-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_1E-DATA652SPLWCU7D, DATA652SPLWCU7D_1F-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_20-DATA652SPLWCU7D, DATA652SPLWCU7D_21-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_22-DATA652SPLWCU7D, DATA652SPLWCU7D_23-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_24-DATA652SPLWCU7D, DATA652SPLWCU7D_25-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_26-DATA652SPLWCU7D, DATA652SPLWCU7D_27-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_28-DATA652SPLWCU7D, DATA652SPLWCU7D_29-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_2A-DATA652SPLWCU7D, DATA652SPLWCU7D_2B-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_2C-DATA652SPLWCU7D, DATA652SPLWCU7D_2D-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_2E-DATA652SPLWCU7D, DATA652SPLWCU7D_2F-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_30-DATA652SPLWCU7D, DATA652SPLWCU7D_31-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_32-DATA652SPLWCU7D, DATA652SPLWCU7D_33-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_34-DATA652SPLWCU7D, DATA652SPLWCU7D_35-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_36-DATA652SPLWCU7D, DATA652SPLWCU7D_37-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_38-DATA652SPLWCU7D, DATA652SPLWCU7D_39-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_3A-DATA652SPLWCU7D, DATA652SPLWCU7D_3B-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_3C-DATA652SPLWCU7D, DATA652SPLWCU7D_3D-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_3E-DATA652SPLWCU7D, DATA652SPLWCU7D_3F-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_40-DATA652SPLWCU7D, DATA652SPLWCU7D_41-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_42-DATA652SPLWCU7D, DATA652SPLWCU7D_43-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_44-DATA652SPLWCU7D, DATA652SPLWCU7D_45-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_46-DATA652SPLWCU7D, DATA652SPLWCU7D_47-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_48-DATA652SPLWCU7D, DATA652SPLWCU7D_49-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_4A-DATA652SPLWCU7D, DATA652SPLWCU7D_4B-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_4C-DATA652SPLWCU7D, DATA652SPLWCU7D_4D-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_4E-DATA652SPLWCU7D, DATA652SPLWCU7D_4F-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_50-DATA652SPLWCU7D, DATA652SPLWCU7D_51-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_52-DATA652SPLWCU7D, DATA652SPLWCU7D_53-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_54-DATA652SPLWCU7D, DATA652SPLWCU7D_55-DATA652SPLWCU7D
	dc.w DATA652SPLWCU7D_56-DATA652SPLWCU7D, DATA652SPLWCU7D_57-DATA652SPLWCU7D
DATA652SPLWCU7D_1: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_2: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_3: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_4: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_5: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATA652SPLWCU7D_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATA652SPLWCU7D_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATA652SPLWCU7D_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATA652SPLWCU7D_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATA652SPLWCU7D_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATA652SPLWCU7D_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATA652SPLWCU7D_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATA652SPLWCU7D_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATA652SPLWCU7D_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATA652SPLWCU7D_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATA652SPLWCU7D_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATA652SPLWCU7D_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATA652SPLWCU7D_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATA652SPLWCU7D_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATA652SPLWCU7D_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATA652SPLWCU7D_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATA652SPLWCU7D_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATA652SPLWCU7D_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATA652SPLWCU7D_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATA652SPLWCU7D_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATA652SPLWCU7D_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATA652SPLWCU7D_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATA652SPLWCU7D_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATA652SPLWCU7D_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA652SPLWCU7D_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA652SPLWCU7D_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA652SPLWCU7D_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA652SPLWCU7D_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA652SPLWCU7D_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA652SPLWCU7D_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA652SPLWCU7D_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA652SPLWCU7D_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA652SPLWCU7D_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA652SPLWCU7D_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA652SPLWCU7D_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA652SPLWCU7D_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA652SPLWCU7D_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA652SPLWCU7D_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA652SPLWCU7D_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA652SPLWCU7D_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATA652SPLWCU7D_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA652SPLWCU7D_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA652SPLWCU7D_37: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_38: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_39: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_3A: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_3B: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $F4
	dc.b $FC, $5, $0, $8, $E4
	dc.b $4, $8, $0, $C, $F4
DATA652SPLWCU7D_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA652SPLWCU7D_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATA652SPLWCU7D_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA652SPLWCU7D_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATA652SPLWCU7D_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA652SPLWCU7D_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA652SPLWCU7D_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA652SPLWCU7D_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA652SPLWCU7D_45: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_46: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_47: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_48: dc.b $6
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
	dc.b $C, $0, $0, $11, $F0
	dc.b $4, $0, $0, $12, $8
DATA652SPLWCU7D_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATA652SPLWCU7D_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATA652SPLWCU7D_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATA652SPLWCU7D_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA652SPLWCU7D_4D: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATA652SPLWCU7D_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATA652SPLWCU7D_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATA652SPLWCU7D_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATA652SPLWCU7D_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATA652SPLWCU7D_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATA652SPLWCU7D_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATA652SPLWCU7D_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATA652SPLWCU7D_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATA652SPLWCU7D_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATA652SPLWCU7D_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even