; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 01 2020 05:48:00 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAOELTQ5RH3R:
	dc.w DATAOELTQ5RH3R_0-DATAOELTQ5RH3R, DATAOELTQ5RH3R_1-DATAOELTQ5RH3R
	dc.w DATAOELTQ5RH3R_2-DATAOELTQ5RH3R, DATAOELTQ5RH3R_3-DATAOELTQ5RH3R
	dc.w DATAOELTQ5RH3R_4-DATAOELTQ5RH3R, DATAOELTQ5RH3R_5-DATAOELTQ5RH3R
	dc.w DATAOELTQ5RH3R_6-DATAOELTQ5RH3R, DATAOELTQ5RH3R_7-DATAOELTQ5RH3R
DATAOELTQ5RH3R_0: dc.b $A
	dc.b $B, $8, $0, $0, $8
	dc.b $13, $F, $0, $3, $8
	dc.b $13, $F, $0, $13, $28
	dc.b $33, $E, $0, $23, $8
	dc.b $33, $E, $0, $2F, $28
	dc.b $4B, $D, $0, $3B, $0
	dc.b $4B, $9, $0, $43, $20
	dc.b $4B, $0, $0, $49, $38
	dc.b $5B, $C, $0, $4A, $8
	dc.b $5B, $0, $0, $4E, $28
DATAOELTQ5RH3R_1: dc.b $F
	dc.b $4B, $E, $1, $BD, $20
	dc.b $3B, $5, $1, $C9, $38
	dc.b $43, $0, $1, $CD, $30
	dc.b $4B, $0, $1, $CE, $40
	dc.b $63, $0, $1, $CF, $20
	dc.b $13, $E, $0, $4F, $8
	dc.b $13, $E, $0, $5B, $28
	dc.b $1B, $1, $0, $67, $48
	dc.b $2B, $2, $0, $69, $0
	dc.b $2B, $F, $0, $6C, $8
	dc.b $2B, $F, $0, $7C, $28
	dc.b $33, $2, $0, $8C, $48
	dc.b $4B, $E, $0, $8F, $10
	dc.b $4B, $9, $0, $9B, $30
	dc.b $5B, $4, $0, $A1, $30
DATAOELTQ5RH3R_2: dc.b $11
	dc.b $3B, $E, $1, $BD, $28
	dc.b $2B, $5, $1, $C9, $40
	dc.b $33, $0, $1, $CD, $38
	dc.b $3B, $0, $1, $CE, $48
	dc.b $53, $0, $1, $CF, $28
	dc.b $23, $F, $1, $A9, $8
	dc.b $23, $3, $1, $B9, $28
	dc.b $13, $E, $0, $4F, $8
	dc.b $13, $E, $0, $5B, $28
	dc.b $1B, $1, $0, $67, $48
	dc.b $2B, $2, $0, $69, $0
	dc.b $2B, $F, $0, $6C, $8
	dc.b $2B, $F, $0, $7C, $28
	dc.b $33, $2, $0, $8C, $48
	dc.b $4B, $E, $0, $8F, $10
	dc.b $48, $9, $0, $9B, $30
	dc.b $58, $4, $0, $A1, $30
DATAOELTQ5RH3R_3: dc.b $D
	dc.b $13, $F, $0, $A3, $8
	dc.b $B, $8, $0, $B3, $28
	dc.b $13, $F, $0, $B6, $28
	dc.b $1B, $0, $0, $C6, $48
	dc.b $23, $6, $0, $C7, $48
	dc.b $3B, $0, $0, $CD, $48
	dc.b $33, $D, $0, $CE, $8
	dc.b $33, $E, $0, $D6, $28
	dc.b $43, $B, $0, $E2, $10
	dc.b $4B, $8, $0, $EE, $28
	dc.b $53, $1, $0, $F1, $8
	dc.b $53, $4, $0, $F3, $28
	dc.b $5B, $0, $0, $F5, $28
DATAOELTQ5RH3R_4: dc.b $B
	dc.b $B, $F, $0, $F6, $10
	dc.b $B, $B, $1, $6, $30
	dc.b $13, $6, $1, $12, $48
	dc.b $2B, $E, $1, $18, $18
	dc.b $2B, $E, $1, $24, $38
	dc.b $2B, $1, $1, $30, $10
	dc.b $43, $E, $1, $32, $10
	dc.b $43, $6, $1, $3E, $30
	dc.b $43, $4, $1, $44, $40
	dc.b $4B, $0, $1, $46, $40
	dc.b $5B, $8, $1, $47, $18
DATAOELTQ5RH3R_5: dc.b $13
	dc.b $2B, $E, $1, $E4, $38
	dc.b $1B, $5, $1, $F0, $48
	dc.b $43, $8, $1, $F4, $38
	dc.b $4B, $4, $1, $F7, $38
	dc.b $13, $F, $1, $4A, $10
	dc.b $B, $4, $1, $5A, $20
	dc.b $3, $B, $1, $5C, $30
	dc.b $B, $0, $1, $68, $48
	dc.b $1B, $0, $1, $69, $48
	dc.b $1B, $5, $1, $6A, $0
	dc.b $2B, $2, $1, $6E, $8
	dc.b $33, $F, $1, $71, $10
	dc.b $23, $D, $1, $81, $30
	dc.b $23, $1, $1, $89, $50
	dc.b $33, $8, $1, $8B, $30
	dc.b $3B, $E, $1, $8E, $30
	dc.b $53, $D, $1, $9A, $8
	dc.b $53, $C, $1, $A2, $28
	dc.b $5B, $8, $1, $A6, $28
DATAOELTQ5RH3R_6: dc.b $15
	dc.b $2B, $E, $1, $E4, $38
	dc.b $1B, $5, $1, $F0, $48
	dc.b $43, $8, $1, $F4, $38
	dc.b $4B, $4, $1, $F7, $38
	dc.b $1B, $F, $1, $D0, $8
	dc.b $1B, $3, $1, $E0, $28
	dc.b $13, $F, $1, $4A, $10
	dc.b $B, $4, $1, $5A, $20
	dc.b $3, $B, $1, $5C, $30
	dc.b $B, $0, $1, $68, $48
	dc.b $1B, $0, $1, $69, $48
	dc.b $1B, $5, $1, $6A, $0
	dc.b $2B, $2, $1, $6E, $8
	dc.b $33, $F, $1, $71, $10
	dc.b $23, $D, $1, $81, $30
	dc.b $23, $1, $1, $89, $50
	dc.b $33, $8, $1, $8B, $30
	dc.b $3B, $E, $1, $8E, $30
	dc.b $53, $D, $1, $9A, $8
	dc.b $53, $C, $1, $A2, $28
	dc.b $5B, $8, $1, $A6, $28
DATAOELTQ5RH3R_7: dc.b $16
	dc.b $1B, $4, $1, $F9, $38
	dc.b $23, $0, $1, $FB, $38
	dc.b $2B, $8, $1, $FC, $30
	dc.b $33, $1, $1, $FF, $30
	dc.b $33, $B, $2, $1, $38
	dc.b $1B, $F, $1, $D0, $8
	dc.b $1B, $3, $1, $E0, $28
	dc.b $13, $F, $1, $4A, $10
	dc.b $B, $4, $1, $5A, $20
	dc.b $3, $B, $1, $5C, $30
	dc.b $B, $0, $1, $68, $48
	dc.b $1B, $0, $1, $69, $48
	dc.b $1B, $5, $1, $6A, $0
	dc.b $2B, $2, $1, $6E, $8
	dc.b $33, $F, $1, $71, $10
	dc.b $23, $D, $1, $81, $30
	dc.b $23, $1, $1, $89, $50
	dc.b $33, $8, $1, $8B, $30
	dc.b $3B, $E, $1, $8E, $30
	dc.b $53, $D, $1, $9A, $8
	dc.b $53, $C, $1, $A2, $28
	dc.b $5B, $8, $1, $A6, $28
	even