; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Mar 11 2020 00:15:46 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA3RVSQS2IY1R:
	dc.w DATA3RVSQS2IY1R_0-DATA3RVSQS2IY1R
DATA3RVSQS2IY1R_0: dc.b $F
	dc.b $E4, $C, $3, $1, $EA
	dc.b $EC, $C, $3, $5, $CA
	dc.b $EC, $C, $3, $9, $EA
	dc.b $EC, $4, $3, $D, $A
	dc.b $F4, $C, $3, $F, $CA
	dc.b $F4, $C, $3, $13, $EA
	dc.b $F4, $4, $3, $17, $A
	dc.b $FC, $C, $3, $19, $CA
	dc.b $FC, $4, $3, $1D, $2
	dc.b $4, $C, $3, $1F, $CA
	dc.b $C, $C, $3, $27, $CA
	dc.b $C, $C, $3, $2B, $EA
	dc.b $14, $C, $3, $2F, $F2
	dc.b $4, $0, $3, $23, $EA
	dc.b $4, $8, $3, $24, $FA
	even