; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Oct 06 2020 16:21:30 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAXHOTEYWF5BO:
	dc.w DATAXHOTEYWF5BO_0-DATAXHOTEYWF5BO
DATAXHOTEYWF5BO_0: dc.b $2E
	dc.b $E5, $C, $0, $51, $B1
	dc.b $E5, $C, $0, $55, $D1
	dc.b $E5, $C, $0, $59, $F1
	dc.b $E5, $C, $0, $5D, $11
	dc.b $E5, $C, $0, $61, $31
	dc.b $ED, $C, $0, $65, $B1
	dc.b $ED, $C, $0, $69, $D1
	dc.b $ED, $C, $0, $6D, $F1
	dc.b $ED, $C, $0, $71, $11
	dc.b $ED, $C, $0, $75, $31
	dc.b $F5, $C, $0, $79, $B9
	dc.b $F5, $C, $0, $7D, $D9
	dc.b $F5, $C, $0, $81, $F9
	dc.b $F5, $C, $0, $85, $19
	dc.b $F5, $8, $0, $89, $39
	dc.b $FD, $C, $0, $8C, $B9
	dc.b $FD, $C, $0, $90, $D9
	dc.b $FD, $C, $0, $94, $F9
	dc.b $FD, $C, $0, $98, $19
	dc.b $FD, $8, $0, $9C, $39
	dc.b $5, $C, $0, $9F, $A1
	dc.b $5, $C, $0, $A3, $C1
	dc.b $5, $C, $0, $A7, $E1
	dc.b $5, $C, $0, $AB, $1
	dc.b $5, $C, $0, $AF, $21
	dc.b $5, $4, $0, $B3, $41
	dc.b $D, $C, $0, $B5, $99
	dc.b $D, $C, $0, $B9, $B9
	dc.b $D, $C, $0, $BD, $D9
	dc.b $D, $C, $0, $C1, $F9
	dc.b $D, $8, $0, $C5, $19
	dc.b $15, $0, $0, $C8, $A1
	dc.b $15, $8, $0, $C9, $B1
	dc.b $15, $C, $0, $CC, $E1
	dc.b $15, $C, $0, $D0, $1
	dc.b $1D, $C, $0, $D4, $99
	dc.b $1D, $4, $0, $D8, $B9
	dc.b $1D, $C, $0, $DA, $E9
	dc.b $1D, $8, $0, $DE, $9
	dc.b $25, $0, $0, $E1, $99
	dc.b $25, $8, $0, $E2, $A9
	dc.b $15, $0, $0, $E5, $A9
	dc.b $25, $0, $0, $E6, $A1
	dc.b $15, $0, $0, $E7, $C9
	dc.b $1D, $0, $0, $E8, $C9
	dc.b $FD, $0, $0, $E9, $B1
	even